name: jinsovik_scanner
description: Jinsovik Сканер - Сканування штрихкодів

version: 1.3.2+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.3
  path_provider: ^2.1.2
  intl: ^0.18.1
  mobile_scanner: ^7.0.1
  http: ^1.2.1
  printing: ^5.12.0
  fluttertoast: ^8.2.2+1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.1
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.3.0
  vibration: ^3.1.3
  # Web-compatible barcode scanning
  js: ^0.6.7
  universal_html: ^2.2.4
  camera_web: ^0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/calibri.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon-app.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "icon-app.png"
    background_color: "#121212"
    theme_color: "#121212"
